version: '3.4'

services:
  sampleproject:
    image: localhost/pizza
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    ports:
      - 9001:9001
